name: PR Validation

on:
  pull_request:
    branches: [ "main", "develop" ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096m -Dorg.gradle.daemon=false"

jobs:
  validate-pr:
    name: Validate Pull Request
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v2

    - name: Check code formatting
      run: ./gradlew ktlintCheck
      continue-on-error: true

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest

    - name: Run lint checks
      run: ./gradlew lintDebug

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Check for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
        extra_args: --debug --only-verified

    - name: Comment PR with build status
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const { context, github } = require('@actions/github');
          const status = '${{ job.status }}';
          const emoji = status === 'success' ? '✅' : '❌';

          const comment = `## ${emoji} Build Status: ${status.toUpperCase()}

          **Build Summary:**
          - Tests: ${{ steps.test.outcome || 'Not run' }}
          - Lint: ${{ steps.lint.outcome || 'Not run' }}
          - APK Build: ${{ steps.build.outcome || 'Not run' }}

          View full details in the [Actions tab](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

  apk-size-check:
    name: APK Size Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Check APK size
      run: |
        APK_SIZE=$(stat -c%s "app/build/outputs/apk/debug/app-debug.apk")
        APK_SIZE_MB=$((APK_SIZE / 1024 / 1024))
        echo "APK_SIZE_MB=$APK_SIZE_MB" >> $GITHUB_ENV
        echo "APK size: ${APK_SIZE_MB}MB"

        if [ $APK_SIZE_MB -gt 50 ]; then
          echo "::warning::APK size (${APK_SIZE_MB}MB) is quite large. Consider optimizing."
        fi

    - name: Comment APK size
      uses: actions/github-script@v7
      with:
        script: |
          const apkSizeMB = process.env.APK_SIZE_MB;
          const sizeEmoji = apkSizeMB > 50 ? '⚠️' : '✅';

          const comment = `## ${sizeEmoji} APK Size Report

          **Debug APK Size:** ${apkSizeMB}MB

          ${apkSizeMB > 50 ? '⚠️ **Warning:** APK size is quite large. Consider optimizing resources and dependencies.' : '✅ APK size looks good!'}`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });